### ISSUE TITLE
User Record from the rabbitMq-Commons is not compatible to rabbitmq-auth-backend-http

### ISSUE THREAD

**Issue by jaydlowrider** [simonmacmullen/rabbitmq-auth-backend-http#8]
Hello,
After cloning this repo, and executing a "make" command. I was getting this error.

src/rabbit_auth_backend_http.erl:44: field auth_backend undefined in record user
src/rabbit_auth_backend_http.erl:45: field impl undefined in record user
src/rabbit_auth_backend_http.erl:20: Warning: behaviour rabbit_auth_backend undefined
make: *** [ebin/rabbit_auth_backend_http.beam] Error 1

Upon further investigation, the UserRecord from rabbitmq-commons is outdated, I've manually changed it, so it will built.

Thanks,
Melvin

**Comment by simonmacmullen** [comment]
Note that the user record for rabbitmq-auth-backend-http matches the one for RabbitMQ 3.4.x, it's only changed on default. If you are planning on running against 3.4.x rather than a nightly build, run "make named_update BRANCH=stable" in umbrella before building, or download a binary from http://www.rabbitmq.com/community-plugins.html
